// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lljnjjlhknturnbwgxkt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxsam5qamxoa250dXJuYndneGt0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NzI5ODgsImV4cCI6MjA3MjE0ODk4OH0.LpI3LUXrsr_LSzVWP22Pxb_y8Rwpq1LMHAecHtayEFU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});